<?php namespace Application\Block\HpProducts;

defined("C5_EXECUTE") or die("Access Denied.");

use AssetList;
use Concrete\Core\Block\BlockController;
use Core;
use Database;
use File;
use Page;
use Permissions;

class Controller extends BlockController
{
    public $btFieldsRequired = ['title', 'subTitle', 'bgColor', 'paddingTop', 'paddingBottom', 'page' => ['pages']];
    protected $btExportPageColumns = ['pages'];
    protected $btExportTables = ['btHpProducts', 'btHpProductsPageEntries'];
    protected $btTable = 'btHpProducts';
    protected $btInterfaceWidth = 400;
    protected $btInterfaceHeight = 500;
    protected $btIgnorePageThemeGridFrameworkContainer = false;
    protected $btCacheBlockRecord = true;
    protected $btCacheBlockOutput = true;
    protected $btCacheBlockOutputOnPost = true;
    protected $btCacheBlockOutputForRegisteredUsers = true;
    protected $pkg = false;

    protected $className = '';

    public function getBlockTypeName()
    {
        return t("Generic List Block");
    }

    public function getSearchableContent()
    {
        $content = [];
        $content[] = $this->title;
        $content[] = $this->subTitle;
        $content[] = $this->bgColor;
        $content[] = $this->paddingTop;
        $content[] = $this->paddingBottom;
        return implode(" ", $content);
    }

    public function on_start()
    {
        parent::on_start(); // TODO: Change the autogenerated stub

        switch($this->getBlockTemplateName())
        {
            case 'products':
                $this->className = 'Application\Concrete\Models\Products\ProductList';
                break;
            case 'applications':
                $this->className = 'Application\Concrete\Models\Application\ApplicationList';
                break;
            case 'case_studies':
                $this->className = 'Application\Concrete\Models\CaseStudies\CaseStudiesList';
                break;
            default:
               $this->className = 'Application\Concrete\Models\Common\CommonList';
                break;
        }
    }

    protected function getBlockTemplateName(){
        if($this->getBlockObject()) return $this->getBlockObject()->getBlockFilename();
        return '';

    }

    public function view()
    {
        $db = Database::connection();
        $link_URL = null;
		$link_Object = null;
		$link_Title = trim($this->link_Title);
		if (trim($this->link) != '') {
			switch ($this->link) {
				case 'page':
					if ($this->link_Page > 0 && ($link_Page_c = Page::getByID($this->link_Page)) && !$link_Page_c->error && !$link_Page_c->isInTrash()) {
						$link_Object = $link_Page_c;
						$link_URL = $link_Page_c->getCollectionLink();
						if ($link_Title == '') {
							$link_Title = $link_Page_c->getCollectionName();
						}
					}
					break;
				case 'file':
					$link_File_id = (int)$this->link_File;
					if ($link_File_id > 0 && ($link_File_object = File::getByID($link_File_id)) && is_object($link_File_object)) {
						$fp = new Permissions($link_File_object);
						if ($fp->canViewFile()) {
							$link_Object = $link_File_object;
							$link_URL = $link_File_object->getRelativePath();
							if ($link_Title == '') {
								$link_Title = $link_File_object->getTitle();
							}
						}
					}
					break;
				case 'url':
					$link_URL = $this->link_URL;
					if ($link_Title == '') {
						$link_Title = $link_URL;
					}
					break;
				case 'relative_url':
					$link_URL = $this->link_Relative_URL;
					if ($link_Title == '') {
						$link_Title = $this->link_Relative_URL;
					}
					break;
				case 'image':
					if ($this->link_Image && ($link_Image_object = File::getByID($this->link_Image)) && is_object($link_Image_object)) {
						$link_URL = $link_Image_object->getURL();
						$link_Object = $link_Image_object;
						if ($link_Title == '') {
							$link_Title = $link_Image_object->getTitle();
						}
					}
					break;
			}
		}
		$this->set("link_URL", $link_URL);
		$this->set("link_Object", $link_Object);
		$this->set("link_Title", $link_Title);
        $pages = [];
        $page_items = $db->fetchAll('SELECT * FROM btHpProductsPageEntries WHERE bID = ? ORDER BY sortOrder', [$this->bID]);
        $page_items = array_map(function ($item) {
            return $item["pages"];
        }, $page_items);


        $commonList = new $this->className();
        $commonList->filterByIDs($page_items);
        $pages = array_reduce($commonList->getResults(), function ($carry, $item) {
            $carry[$item->getID()] = $item;
            return $carry;
        }, []);

        foreach ($page_items as $key => $pageID) {
            if(isset($pages[$pageID]))$page_items[$key] = $pages[$pageID];
            else unset($page_items[$key]);
        }

        $this->set('pages', $page_items);
    }

    public function delete()
    {
        $db = Database::connection();
        $db->delete('btHpProductsPageEntries', ['bID' => $this->bID]);
        parent::delete();
    }

    public function duplicate($newBID)
    {
        $db = Database::connection();
        $page_items = $db->fetchAll('SELECT * FROM btHpProductsPageEntries WHERE bID = ? ORDER BY sortOrder', [$this->bID]);
        foreach ($page_items as $page_item) {
            unset($page_item['id']);
            $page_item['bID'] = $newBID;
            $db->insert('btHpProductsPageEntries', $page_item);
        }
        parent::duplicate($newBID);
    }

    public function add()
    {
        $this->addEdit();
        $page = $this->get('page');
        $this->set('page_items', []);
        $this->set('page', $page);
    }

    public function edit()
    {
        $db = Database::connection();
        $this->addEdit();
        $page = $this->get('page');
        $page_items = $db->fetchAll('SELECT * FROM btHpProductsPageEntries WHERE bID = ? ORDER BY sortOrder', [$this->bID]);
        $this->set('page', $page);
        $this->set('page_items', $page_items);
    }

    protected function addEdit()
    {
        $this->set("link_Options", $this->getSmartLinkTypeOptions([
  'page',
  'file',
  'image',
  'url',
  'relative_url',
], true));
        $page = [];
        $this->set('page', $page);
        $this->set('identifier', new \Concrete\Core\Utility\Service\Identifier());
        $al = AssetList::getInstance();
        $al->register('css', 'repeatable-ft.form', 'blocks/hp_products/css_form/repeatable-ft.form.css', [], $this->pkg);
        $al->register('javascript', 'handlebars', 'blocks/hp_products/js_form/handlebars-v4.0.4.js', [], $this->pkg);
        $al->register('javascript', 'handlebars-helpers', 'blocks/hp_products/js_form/handlebars-helpers.js', [], $this->pkg);
        $this->requireAsset('core/sitemap');
        $this->requireAsset('css', 'repeatable-ft.form');
        $this->requireAsset('javascript', 'handlebars');
        $this->requireAsset('javascript', 'handlebars-helpers');
        $this->set('btFieldsRequired', $this->btFieldsRequired);
        $this->set('identifier_getString', Core::make('helper/validation/identifier')->getString(18));
    }

    public function save($args)
    {
        $db = Database::connection();
        if (isset($args["link"]) && trim($args["link"]) != '') {
			switch ($args["link"]) {
				case 'page':
					$args["link_File"] = '0';
					$args["link_URL"] = '';
					$args["link_Relative_URL"] = '';
					$args["link_Image"] = '0';
					break;
				case 'file':
					$args["link_Page"] = '0';
					$args["link_URL"] = '';
					$args["link_Relative_URL"] = '';
					$args["link_Image"] = '0';
					break;
				case 'url':
					$args["link_Page"] = '0';
					$args["link_Relative_URL"] = '';
					$args["link_File"] = '0';
					$args["link_Image"] = '0';
					break;
				case 'relative_url':
					$args["link_Page"] = '0';
					$args["link_URL"] = '';
					$args["link_File"] = '0';
					$args["link_Image"] = '0';
					break;
				case 'image':
					$args["link_Page"] = '0';
					$args["link_File"] = '0';
					$args["link_URL"] = '';
					$args["link_Relative_URL"] = '';
					break;
				default:
					$args["link_Title"] = '';
					$args["link_Page"] = '0';
					$args["link_File"] = '0';
					$args["link_URL"] = '';
					$args["link_Relative_URL"] = '';
					$args["link_Image"] = '0';
					break;	
			}
		}
		else {
			$args["link_Title"] = '';
			$args["link_Page"] = '0';
			$args["link_File"] = '0';
			$args["link_URL"] = '';
			$args["link_Relative_URL"] = '';
			$args["link_Image"] = '0';
		}
        $rows = $db->fetchAll('SELECT * FROM btHpProductsPageEntries WHERE bID = ? ORDER BY sortOrder', [$this->bID]);
        $page_items = isset($args['page']) && is_array($args['page']) ? $args['page'] : [];
        $queries = [];
        if (!empty($page_items)) {
            $i = 0;
            foreach ($page_items as $page_item) {
                $data = [
                    'sortOrder' => $i + 1,
                ];
                if (isset($page_item['pages']) && trim($page_item['pages']) != '' && (($page_item['pages_c'] = Page::getByID($page_item['pages'])) && !$page_item['pages_c']->error)) {
                    $data['pages'] = trim($page_item['pages']);
                } else {
                    $data['pages'] = null;
                }
                if (isset($page_item['pages_text']) && trim($page_item['pages_text']) != '') {
                    $data['pages_text'] = trim($page_item['pages_text']);
                } else {
                    $data['pages_text'] = null;
                }
                if (isset($rows[$i])) {
                    $queries['update'][$rows[$i]['id']] = $data;
                    unset($rows[$i]);
                } else {
                    $data['bID'] = $this->bID;
                    $queries['insert'][] = $data;
                }
                $i++;
            }
        }
        if (!empty($rows)) {
            foreach ($rows as $row) {
                $queries['delete'][] = $row['id'];
            }
        }
        if (!empty($queries)) {
            foreach ($queries as $type => $values) {
                if (!empty($values)) {
                    switch ($type) {
                        case 'update':
                            foreach ($values as $id => $data) {
                                $db->update('btHpProductsPageEntries', $data, ['id' => $id]);
                            }
                            break;
                        case 'insert':
                            foreach ($values as $data) {
                                $db->insert('btHpProductsPageEntries', $data);
                            }
                            break;
                        case 'delete':
                            foreach ($values as $value) {
                                $db->delete('btHpProductsPageEntries', ['id' => $value]);
                            }
                            break;
                    }
                }
            }
        }
        parent::save($args);
    }

    public function validate($args)
    {
        $e = Core::make("helper/validation/error");
        if (in_array("title", $this->btFieldsRequired) && (trim($args["title"]) == "")) {
            $e->add(t("The %s field is required.", t("Title")));
        }
        if (in_array("subTitle", $this->btFieldsRequired) && (trim($args["subTitle"]) == "")) {
            $e->add(t("The %s field is required.", t("Sub Title")));
        }
        if ((in_array("link", $this->btFieldsRequired) && (!isset($args["link"]) || trim($args["link"]) == "")) || (isset($args["link"]) && trim($args["link"]) != "" && !array_key_exists($args["link"], $this->getSmartLinkTypeOptions(['page', 'file', 'image', 'url', 'relative_url'])))) {
			$e->add(t("The %s field has an invalid value.", t("Link")));
		} elseif (array_key_exists($args["link"], $this->getSmartLinkTypeOptions(['page', 'file', 'image', 'url', 'relative_url']))) {
			switch ($args["link"]) {
				case 'page':
					if (!isset($args["link_Page"]) || trim($args["link_Page"]) == "" || $args["link_Page"] == "0" || (($page = Page::getByID($args["link_Page"])) && $page->error !== false)) {
						$e->add(t("The %s field for '%s' is required.", t("Page"), t("Link")));
					}
					break;
				case 'file':
					if (!isset($args["link_File"]) || trim($args["link_File"]) == "" || !is_object(File::getByID($args["link_File"]))) {
						$e->add(t("The %s field for '%s' is required.", t("File"), t("Link")));
					}
					break;
				case 'url':
					if (!isset($args["link_URL"]) || trim($args["link_URL"]) == "" || !filter_var($args["link_URL"], FILTER_VALIDATE_URL)) {
						$e->add(t("The %s field for '%s' does not have a valid URL.", t("URL"), t("Link")));
					}
					break;
				case 'relative_url':
					if (!isset($args["link_Relative_URL"]) || trim($args["link_Relative_URL"]) == "") {
						$e->add(t("The %s field for '%s' is required.", t("Relative URL"), t("Link")));
					}
					break;
				case 'image':
					if (!isset($args["link_Image"]) || trim($args["link_Image"]) == "" || !is_object(File::getByID($args["link_Image"]))) {
						$e->add(t("The %s field for '%s' is required.", t("Image"), t("Link")));
					}
					break;	
			}
		}
        $pageEntriesMin = 0;
        $pageEntriesMax = 0;
        $pageEntriesErrors = 0;
        $page = [];
        if (isset($args['page']) && is_array($args['page']) && !empty($args['page'])) {
            if ($pageEntriesMin >= 1 && count($args['page']) < $pageEntriesMin) {
                $e->add(t("The %s field requires at least %s entries, %s entered.", t("Pages"), $pageEntriesMin, count($args['page'])));
                $pageEntriesErrors++;
            }
            if ($pageEntriesMax >= 1 && count($args['page']) > $pageEntriesMax) {
                $e->add(t("The %s field is set to a maximum of %s entries, %s entered.", t("Pages"), $pageEntriesMax, count($args['page'])));
                $pageEntriesErrors++;
            }
            if ($pageEntriesErrors == 0) {
                foreach ($args['page'] as $page_k => $page_v) {
                    if (is_array($page_v)) {
                        if ((in_array("pages", $this->btFieldsRequired['page']) || (isset($page_v['pages']) && trim($page_v['pages']) != '')) && (trim($page_v['pages']) == "" || (($page = Page::getByID($page_v['pages'])) && $page->error !== false))) {
                            $e->add(t("The %s field is required (%s, row #%s).", t("Pages"), t("Pages"), $page_k));
                        }
                    } else {
                        $e->add(t("The values for the %s field, row #%s, are incomplete.", t('Pages'), $page_k));
                    }
                }
            }
        } else {
            if ($pageEntriesMin >= 1) {
                $e->add(t("The %s field requires at least %s entries, none entered.", t("Pages"), $pageEntriesMin));
            }
        }
        return $e;
    }

    public function composer()
    {
        $al = AssetList::getInstance();
        $al->register('javascript', 'auto-js-' . $this->btHandle, 'blocks/' . $this->btHandle . '/auto.js', [], $this->pkg);
        $this->requireAsset('javascript', 'auto-js-' . $this->btHandle);
        $this->edit();
    }

    protected function getSmartLinkTypeOptions($include = [], $checkNone = false)
	{
		$options = [
			''             => sprintf("-- %s--", t("None")),
			'page'         => t("Page"),
			'url'          => t("External URL"),
			'relative_url' => t("Relative URL"),
			'file'         => t("File"),
			'image'        => t("Image")
		];
		if ($checkNone) {
            $include = array_merge([''], $include);
        }
		$return = [];
		foreach($include as $v){
		    if(isset($options[$v])){
		        $return[$v] = $options[$v];
		    }
		}
		return $return;
	}
}